[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "sphinx-pyproject"
version = "0.0.0"
description = "Move some of your Sphinx configuration into pyproject.toml"
readme = "README.rst"
keywords = [ "sphinx", "documentation", "pep621", "toml",]
dynamic = [ "requires-python", "classifiers", "dependencies",]

[[project.authors]]
email = "dominic@davis-foster.co.uk"
name = "Dominic Davis-Foster"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/sphinx-toolbox/sphinx-pyproject"
"Issue Tracker" = "https://github.com/sphinx-toolbox/sphinx-pyproject/issues"
"Source Code" = "https://github.com/sphinx-toolbox/sphinx-pyproject"
Documentation = "https://sphinx-pyproject.readthedocs.io/en/latest"

[tool.whey]
base-classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: Sphinx",
    "Intended Audience :: Developers",
    "Topic :: Documentation",
    "Topic :: Documentation :: Sphinx",
    "Topic :: Software Development :: Documentation",
    "Topic :: Utilities",
    "Typing :: Typed",
]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython", "PyPy",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "MIT"
package = "sphinx_pyproject"

[tool.sphinx-pyproject]
github_username = "sphinx-toolbox"
github_repository = "sphinx-pyproject"
copyright = "2021 Dominic Davis-Foster"
language = "en"
package_root = "sphinx_pyproject"
extensions = [
    "sphinx_toolbox",
    "sphinx_toolbox.more_autodoc",
    "sphinx_toolbox.more_autosummary",
    "sphinx_toolbox.documentation_summary",
    "sphinx_toolbox.tweaks.param_dash",
    "sphinx_toolbox.tweaks.latex_toc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.mathjax",
    "sphinxcontrib.httpdomain",
    "sphinxcontrib.extras_require",
    "sphinx.ext.todo",
    "sphinxemoji.sphinxemoji",
    "notfound.extension",
    "sphinx_copybutton",
    "sphinxcontrib.default_values",
    "sphinxcontrib.toctree_plus",
    "sphinx_debuginfo",
    "seed_intersphinx_mapping",
]
sphinxemoji_style = "twemoji"
gitstamp_fmt = "%d %b %Y"
templates_path = [ "_templates",]
html_static_path = [ "_static",]
source_suffix = ".rst"
master_doc = "index"
suppress_warnings = [ "image.nonlocal_uri",]
pygments_style = "default"
html_theme = "domdf_sphinx_theme"
html_theme_path = [ "../..",]
html_show_sourcelink = true
add_module_names = false
hide_none_rtype = true
all_typevars = true
overloads_location = "bottom"
autodoc_exclude_members = [
    "__dict__",
    "__class__",
    "__dir__",
    "__weakref__",
    "__module__",
    "__annotations__",
    "__orig_bases__",
    "__parameters__",
    "__subclasshook__",
    "__init_subclass__",
    "__attrs_attrs__",
    "__init__",
    "__new__",
    "__getnewargs__",
    "__abstractmethods__",
    "__hash__",
]
toctree_plus_types = [
    "class",
    "function",
    "method",
    "data",
    "enum",
    "flag",
    "confval",
    "directive",
    "role",
    "confval",
    "protocol",
    "typeddict",
    "namedtuple",
    "exception",
]

[tool.sphinx-pyproject.html_theme_options]
logo_only = false

[tool.sphinx-pyproject.html_context]
display_github = true
github_user = "sphinx-toolbox"
github_repo = "sphinx-pyproject"
github_version = "master"
conf_py_path = "/doc-source/"
